import Nav from "@/components/Nav"
import Header from "@/components/Header"
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <div className="flex min-h-screen w-full flex-col bg-muted/40">
          <Nav />
          <div className="flex flex-col sm:gap-4 sm:py-4 sm:pl-14">
        
            <Header />

            <main className="grid flex-1 items-start p-4 sm:px-6 sm:py-0 md:gap-8">
              {children}
            </main>

          </div>
        </div>

      </body>
    </html>
  );
}
